import React, { useContext } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Store } from '../utils/Store'

export default function Layout({title, children}) {
  const [ state, dispatch ] = useContext(Store);
  const { cart } = state;
   
  return (
    <>
      <Head>
        <title>{title ? title +  ' - Amazon' : 'Amazon'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="E-commerce, Retail" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex flex-col  min-h-screen justify-between '>
        <header>
          <nav className='flex items-center justify-between px-4 shadow-md h-12'>
            <Link href='/'>
              <a className='text-lg font-bold text-emerald-500'>amazon</a>
            </Link>
            <div>
                <Link href='/cart'>
                  <a className='p-2'> 
                  Cart
                  {cart.cartItems.length > 0 && (
                    <span className='ml-1 rounded-full bg-black px-2 py-1 font-xs font-bold text-white'>
                      {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                    </span>
                  )}
                  </a>
                </Link>
                <Link href='/login'><a className='text-sm'>Login</a></Link>
            </div>
          </nav>
        </header>
        <main className='container m-auto px-4 mt-4'>
          {children}
        </main>
        <footer className='flex justify-center items-center shadow-inner h-10'>
          <p>Copyright &copy; 2022 Amazon</p>
        </footer>
      </div>

      
    </>
  )
}
